import { projectCodeFiles, projectLabel } from "./generatedProjectData";

export type PageKey = "dashboard" | "roles" | "flows" | "code" | "theory" | "tests" | "interview" | "about";
export type RoleKey = "Bidder" | "Seller" | "Admin";
export type StudyStatus = "done" | "review" | "risk";

export type StudyTopic = {
  id: string;
  title: string;
  category: string;
  level: string;
  status: StudyStatus;
  summary: string;
  projectExample: string;
  files: string[];
  links: { label: string; url: string }[];
};

export type RolePath = {
  role: RoleKey;
  goal: string;
  permissions: string[];
  mustKnow: string[];
  journey: { step: string; client: string; server: string; data: string }[];
};

export type ScenarioStep = {
  id: string;
  order: number;
  module: "client" | "common" | "server";
  badge: string;
  title: string;
  summary: string;
  path: string;
  layer: string;
  role?: string;
  trigger?: string;
  input?: string;
  output?: string;
  meaning: string;
  whyItMatters?: string;
  failureMode?: string;
  links: string[];
  nextLinks?: string[];
  codeNotes: { line: number; code: string; note: string }[];
};

export type ScenarioFlow = {
  id: string;
  label: string;
  title: string;
  subtitle: string;
  steps: ScenarioStep[];
};

export type TestCase = {
  name: string;
  target: string;
  command: string;
  arrange: string;
  act: string;
  assert: string;
  viva: string;
};

const FILE = {
  rootPom: "pom.xml",
  readme: "README.md",
  designDoc: "DESIGN.md",
  architectureDoc: "docs/Project_Architecture_Deep_Dive.md",
  authContractDoc: "docs/USER_AUTH_CONTRACT.md",
  runServerDoc: "docs/RUN_SERVER_LOCAL.md",
  loginView: "auction-client/src/main/resources/view/login.fxml",
  registerView: "auction-client/src/main/resources/view/register.fxml",
  auctionListView: "auction-client/src/main/resources/view/auction_list.fxml",
  auctionDetailView: "auction-client/src/main/resources/view/auction_detail.fxml",
  createItemView: "auction-client/src/main/resources/view/create_item.fxml",
  sellerDashboardView: "auction-client/src/main/resources/view/seller_dashboard.fxml",
  adminView: "auction-client/src/main/resources/view/admin.fxml",
  loginController: "auction-client/src/main/java/com/auction/client/controller/LoginController.java",
  registerController: "auction-client/src/main/java/com/auction/client/controller/RegisterController.java",
  auctionListController: "auction-client/src/main/java/com/auction/client/controller/AuctionListController.java",
  auctionDetailController: "auction-client/src/main/java/com/auction/client/controller/AuctionDetailController.java",
  createItemController: "auction-client/src/main/java/com/auction/client/controller/CreateItemController.java",
  sellerDashboardController: "auction-client/src/main/java/com/auction/client/controller/SellerDashboardController.java",
  adminController: "auction-client/src/main/java/com/auction/client/controller/AdminController.java",
  networkClient: "auction-client/src/main/java/com/auction/client/network/NetworkClient.java",
  actionEnum: "auction-common/src/main/java/com/auction/common/message/Action.java",
  clientRequest: "auction-common/src/main/java/com/auction/common/message/ClientRequest.java",
  clientResponse: "auction-common/src/main/java/com/auction/common/message/ClientResponse.java",
  registerRequest: "auction-common/src/main/java/com/auction/common/message/RegisterRequest.java",
  loginRequest: "auction-common/src/main/java/com/auction/common/message/LoginRequest.java",
  createItemRequest: "auction-common/src/main/java/com/auction/common/message/CreateItemRequest.java",
  createAuctionRequest: "auction-common/src/main/java/com/auction/common/message/CreateAuctionRequest.java",
  getAuctionsRequest: "auction-common/src/main/java/com/auction/common/message/GetAuctionsRequest.java",
  getBidHistoryRequest: "auction-common/src/main/java/com/auction/common/message/GetBidHistoryRequest.java",
  placeBidRequest: "auction-common/src/main/java/com/auction/common/message/PlaceBidRequest.java",
  registerAutoBidRequest: "auction-common/src/main/java/com/auction/common/message/RegisterAutoBidRequest.java",
  removeAutoBidRequest: "auction-common/src/main/java/com/auction/common/message/RemoveAutoBidRequest.java",
  cancelAuctionRequest: "auction-common/src/main/java/com/auction/common/message/CancelAuctionRequest.java",
  getAllUsersRequest: "auction-common/src/main/java/com/auction/common/message/GetAllUsersRequest.java",
  banUserRequest: "auction-common/src/main/java/com/auction/common/message/BanUserRequest.java",
  unbanUserRequest: "auction-common/src/main/java/com/auction/common/message/UnbanUserRequest.java",
  serverPushMessage: "auction-common/src/main/java/com/auction/common/message/ServerPushMessage.java",
  registrationPolicy: "auction-common/src/main/java/com/auction/common/message/RegistrationPolicy.java",
  itemFactory: "auction-common/src/main/java/com/auction/common/factory/ItemFactory.java",
  manualBidStrategy: "auction-common/src/main/java/com/auction/common/strategy/ManualBidStrategy.java",
  autoBidStrategy: "auction-common/src/main/java/com/auction/common/strategy/AutoBidStrategy.java",
  auctionStatus: "auction-common/src/main/java/com/auction/common/enums/AuctionStatus.java",
  userRole: "auction-common/src/main/java/com/auction/common/enums/UserRole.java",
  auctionEntity: "auction-common/src/main/java/com/auction/common/entity/Auction.java",
  itemEntity: "auction-common/src/main/java/com/auction/common/entity/Item.java",
  bidTransactionEntity: "auction-common/src/main/java/com/auction/common/entity/BidTransaction.java",
  clientHandler: "auction-server/src/main/java/com/auction/server/handler/ClientHandler.java",
  clientRegistry: "auction-server/src/main/java/com/auction/server/handler/ClientRegistry.java",
  userService: "auction-server/src/main/java/com/auction/server/service/UserService.java",
  itemService: "auction-server/src/main/java/com/auction/server/service/ItemService.java",
  auctionService: "auction-server/src/main/java/com/auction/server/service/AuctionService.java",
  bidService: "auction-server/src/main/java/com/auction/server/service/BidService.java",
  autoBidService: "auction-server/src/main/java/com/auction/server/service/AutoBidService.java",
  auctionScheduler: "auction-server/src/main/java/com/auction/server/service/AuctionScheduler.java",
  dataStore: "auction-server/src/main/java/com/auction/server/datastore/DataStore.java",
  serializableAuctionRepository: "auction-server/src/main/java/com/auction/server/repository/SerializableAuctionRepository.java",
  serializableBidRepository: "auction-server/src/main/java/com/auction/server/repository/SerializableBidRepository.java",
  serializableItemRepository: "auction-server/src/main/java/com/auction/server/repository/SerializableItemRepository.java",
  serializableUserRepository: "auction-server/src/main/java/com/auction/server/repository/SerializableUserRepository.java",
  auctionEventManager: "auction-server/src/main/java/com/auction/server/observer/AuctionEventManager.java",
  broadcastObserver: "auction-server/src/main/java/com/auction/server/observer/BroadcastObserver.java",
  userServiceTest: "auction-server/src/test/java/com/auction/server/service/UserServiceTest.java",
  itemServiceTest: "auction-server/src/test/java/com/auction/server/service/ItemServiceTest.java",
  auctionServiceTest: "auction-server/src/test/java/com/auction/server/service/AuctionServiceTest.java",
  bidServiceTest: "auction-server/src/test/java/com/auction/server/service/BidServiceTest.java",
  bidConcurrencyTest: "auction-server/src/test/java/com/auction/server/service/BidServiceConcurrencyTest.java",
  auctionSchedulerTest: "auction-server/src/test/java/com/auction/server/service/AuctionSchedulerTest.java",
  repositoryTest: "auction-server/src/test/java/com/auction/server/repository/RepositoryTest.java",
  clientHandlerTest: "auction-server/src/test/java/com/auction/server/handler/ClientHandlerTest.java",
  auctionE2eTest: "auction-server/src/test/java/com/auction/server/e2e/AuctionE2ETest.java",
} as const;

const projectFileByPath = new Map(projectCodeFiles.map((file) => [file.path, file] as const));

function uniqueStrings(values: string[]) {
  return Array.from(new Set(values.filter(Boolean)));
}

function file(path: string) {
  return projectFileByPath.get(path);
}

function refs(path: string, patterns: string[] = [], limit = 3) {
  const source = file(path);
  if (!source) return [];
  const pool = source.importantLines.length
    ? source.importantLines
    : source.methods.map((method) => ({
        line: method.line,
        code: method.code,
        explain: `Method ${method.name} là điểm thực thi chính của file.`,
      }));
  if (!pool.length) return [];
  const needles = patterns.map((pattern) => pattern.toLowerCase());
  const matched = needles.length
    ? pool.filter((entry) => needles.some((needle) => `${entry.code} ${entry.explain}`.toLowerCase().includes(needle)))
    : pool;
  const selected = (matched.length ? matched : pool).slice(0, limit);
  return selected.map((entry) => ({
    line: entry.line,
    code: entry.code,
    note: entry.explain,
  }));
}

function flowStep(config: {
  id: string;
  order: number;
  module: "client" | "common" | "server";
  badge: string;
  title: string;
  summary: string;
  path: string;
  role?: string;
  trigger?: string;
  input?: string;
  output?: string;
  meaning: string;
  whyItMatters?: string;
  failureMode?: string;
  links?: string[];
  nextLinks?: string[];
  refPatterns?: string[];
  codeNoteLimit?: number;
}): ScenarioStep {
  const source = file(config.path);
  return {
    id: config.id,
    order: config.order,
    module: config.module,
    badge: config.badge,
    title: config.title,
    summary: config.summary,
    path: config.path,
    layer: source?.layer ?? config.badge,
    role: config.role,
    trigger: config.trigger,
    input: config.input,
    output: config.output,
    meaning: config.meaning,
    whyItMatters: config.whyItMatters,
    failureMode: config.failureMode,
    links: uniqueStrings([config.path, ...(config.links ?? [])]),
    nextLinks: config.nextLinks,
    codeNotes: refs(config.path, config.refPatterns, config.codeNoteLimit ?? 3),
  };
}

export const readiness = [
  { subject: "Contract", score: 92 },
  { subject: "Auth", score: 88 },
  { subject: "Bidding", score: 91 },
  { subject: "Realtime", score: 86 },
  { subject: "Persistence", score: 84 },
  { subject: "Testing", score: 89 },
];

export const milestones = [
  { label: "Nói đúng module", value: 95 },
  { label: "Trace login/register", value: 90 },
  { label: "Trace create item", value: 87 },
  { label: "Giải thích place bid", value: 93 },
  { label: "Giải thích observer/scheduler", value: 86 },
  { label: "Dùng test làm bằng chứng", value: 88 },
];

export const redZones = [
  "Đừng gọi đây là REST/JSON API. Repo hiện tại dùng raw TCP socket + Java Serialization.",
  "Đừng nói dự án đang lưu SQL/SQLite. Nguồn thật lưu trong DataStore và file data/auction_data.dat.",
  "Tự đăng ký ADMIN chỉ bị chặn rõ ở UI/docs; khi vấn đáp nên nói thêm rủi ro drift nếu server branch chưa chặn đủ.",
  "README nhắc top-up/balance như feature tổng quan, nhưng nhánh source đang deploy không có Action TOP_UP riêng; đừng hứa flow không tồn tại.",
  "Auto-bid và realtime chỉ đúng khi nói cùng observer/event manager, không nên tách thành hai cơ chế độc lập.",
];

export const rolePaths: RolePath[] = [
  {
    role: "Bidder",
    goal: "Đăng nhập, xem phiên đang chạy, đặt giá thủ công hoặc auto-bid và đọc realtime update đúng lúc.",
    permissions: ["LOGIN", "GET_AUCTIONS", "GET_AUCTION", "PLACE_BID", "GET_BID_HISTORY", "REGISTER_AUTO_BID", "REMOVE_AUTO_BID"],
    mustKnow: [
      "NetworkClient phân tách ClientResponse và ServerPushMessage trên cùng socket.",
      "BidService giữ lock theo auctionId để chống lost update.",
      "AuctionDetailController phải unregister push listener khi rời màn.",
      "AutoBidService chỉ phản ứng sau khi một bid hợp lệ đã được lưu và notify observer.",
    ],
    journey: [
      {
        step: "Login và nhận AuthUserData",
        client: "login.fxml -> LoginController -> NetworkClient.loginAsync",
        server: "ClientHandler.LOGIN -> UserService.login",
        data: "ClientResponse(success, message, AuthUserData)",
      },
      {
        step: "Xem list/detail auction",
        client: "auction_list.fxml -> AuctionListController -> auction_detail.fxml",
        server: "GET_AUCTIONS / GET_AUCTION -> AuctionService",
        data: "Auction entity + currentPrice + endTime",
      },
      {
        step: "Place bid / auto-bid",
        client: "AuctionDetailController tạo PlaceBidRequest hoặc RegisterAutoBidRequest",
        server: "ClientHandler -> BidService / AutoBidService",
        data: "BidTransaction, AutoBid config, currentPrice mới",
      },
      {
        step: "Nhận realtime push",
        client: "PushListener cập nhật priceLabel/timeLabel trên JavaFX thread",
        server: "AuctionEventManager -> BroadcastObserver -> ClientRegistry.broadcast",
        data: "ServerPushMessage(NEW_BID, PRICE_UPDATE, AUCTION_ENDED)",
      },
    ],
  },
  {
    role: "Seller",
    goal: "Tạo item đúng loại, để server tự sinh auction và hiểu rõ đường đi từ UI tới scheduler.",
    permissions: ["LOGIN", "GET_ITEMS", "CREATE_ITEM", "UPDATE_ITEM", "DELETE_ITEM", "CREATE_AUCTION"],
    mustKnow: [
      "CreateItemController gửi durationMinutes và imagePath trong extraAttributes.",
      "ItemService dùng ItemFactory để tạo đúng subclass Item theo ItemType.",
      "Create item hiện tại tự tạo auction và gọi AuctionScheduler.start/end ngay trên server.",
      "UPDATE/DELETE đi qua SerializableItemRepository chứ không chỉnh DataStore trực tiếp ở UI.",
    ],
    journey: [
      {
        step: "Đăng nhập seller",
        client: "LoginController route sang seller_dashboard.fxml",
        server: "UserService.login",
        data: "AuthUserData(role=SELLER)",
      },
      {
        step: "Mở create_item.fxml và nhập dữ liệu",
        client: "CreateItemController.handleCreateItem",
        server: "ClientHandler.CREATE_ITEM -> ItemService.C",
        data: "CreateItemRequest(name, price, type, durationMinutes, imagePath)",
      },
      {
        step: "Server lưu item + tạo auction",
        client: "Chỉ chờ ClientResponse",
        server: "SerializableItemRepository.save -> SerializableAuctionRepository.save",
        data: "Item mới + Auction OPEN có start/end time",
      },
      {
        step: "Scheduler tự điều khiển lifecycle",
        client: "Seller chỉ thấy kết quả qua list/detail hoặc push message",
        server: "AuctionScheduler.scheduleAuctionStart / scheduleAuctionEndAt",
        data: "AuctionStatus OPEN -> RUNNING -> FINISHED",
      },
    ],
  },
  {
    role: "Admin",
    goal: "Quản trị người dùng và phiên đấu giá, giải thích đúng permission boundary ở server.",
    permissions: ["LOGIN", "GET_USERS", "BAN_USER", "UNBAN_USER", "CANCEL_AUCTION"],
    mustKnow: [
      "Client có thể ẩn hiện màn admin, nhưng server mới là nơi check UserRole.ADMIN.",
      "ClientHandler.validate payload trước rồi mới gọi UserService/AuctionService.",
      "Ban/unban và cancel auction đều trả ClientResponse thay vì ném state trực tiếp cho UI.",
      "Cancel auction còn phải notifyStatusChanged + notifyAuctionEnded để client nhận push phù hợp.",
    ],
    journey: [
      {
        step: "Login với default admin",
        client: "LoginController route sang admin.fxml",
        server: "UserService.login + DataStore.ensureDefaultAdminAccount",
        data: "AuthUserData(role=ADMIN)",
      },
      {
        step: "Ban hoặc unban user",
        client: "Admin screen hoặc request tool tạo BanUserRequest / UnbanUserRequest",
        server: "ClientHandler -> UserService.banUser / unbanUser",
        data: "ClientResponse + SerializableUserRepository.update",
      },
      {
        step: "Cancel auction",
        client: "Admin action tạo CancelAuctionRequest",
        server: "ClientHandler -> AuctionService.cancelAuction",
        data: "AuctionStatus.CANCELED + push AUCTION_ENDED",
      },
    ],
  },
];

export const placeBidFlow = [
  {
    id: "bid-ui",
    lane: "Client" as const,
    title: "AuctionDetailController.handlePlaceBid",
    detail: "Đọc amount từ TextField, lấy current user từ NetworkClient và tạo PlaceBidRequest.",
    file: FILE.auctionDetailController,
  },
  {
    id: "bid-socket",
    lane: "Socket" as const,
    title: "NetworkClient.sendRequestAsync",
    detail: "Gửi ClientRequest(Action.PLACE_BID) qua ObjectOutputStream và chờ ClientResponse từ queue.",
    file: FILE.networkClient,
  },
  {
    id: "bid-handler",
    lane: "Service" as const,
    title: "ClientHandler.handlePlaceBid",
    detail: "Check payload, tách manual bid và auto-bid, rồi dispatch sang BidService hoặc AutoBidService.",
    file: FILE.clientHandler,
  },
  {
    id: "bid-persistence",
    lane: "Repository" as const,
    title: "BidService + repository update",
    detail: "Giữ lock theo auction, save BidTransaction và update Auction qua repository.",
    file: FILE.bidService,
  },
  {
    id: "bid-realtime",
    lane: "Realtime" as const,
    title: "Observer broadcast + client push listener",
    detail: "AuctionEventManager phát event, BroadcastObserver gửi ServerPushMessage và AuctionDetailController cập nhật UI.",
    file: FILE.broadcastObserver,
  },
];

export const scenarioFlows: ScenarioFlow[] = [
  {
    id: "register",
    label: "REGISTER",
    title: "REGISTER: từ register.fxml tới UserService.signup",
    subtitle: "Luồng tự đăng ký phải nói được UI constraint, request contract và nơi validation thật sự diễn ra.",
    steps: [
      flowStep({
        id: "register-view",
        order: 1,
        module: "client",
        badge: "UI",
        title: "register.fxml khởi tạo form",
        summary: "FXML bind RegisterController và expose các action handleRegister/goBack.",
        path: FILE.registerView,
        role: "JavaFX view",
        trigger: "Người dùng mở màn register từ login.",
        input: "username, password, email, role",
        output: "Event onAction sang RegisterController",
        meaning: "View chỉ mô tả cấu trúc form, không tự sinh business rule.",
        whyItMatters: "Nếu fx:controller hoặc onAction sai, luồng register chết từ UI trước khi chạm socket.",
        failureMode: "Sai fx:id/onAction khiến click không chạy hoặc roleBox không được bind.",
        links: [FILE.registerController],
        nextLinks: ["RegisterController.handleRegister"],
        refPatterns: ["fx:controller", "handleRegister", "goBack"],
      }),
      flowStep({
        id: "register-controller",
        order: 2,
        module: "client",
        badge: "UI",
        title: "RegisterController đóng gói input thành RegisterRequest",
        summary: "Controller kiểm tra field trống, chỉ cho BIDDER/SELLER và tạo ClientRequest(Action.REGISTER).",
        path: FILE.registerController,
        role: "JavaFX controller",
        trigger: "User bấm Register.",
        input: "Form input + roleBox value",
        output: "RegisterRequest và ClientRequest(Action.REGISTER)",
        meaning: "Đây là bridge từ form JavaFX sang contract common, nhưng chưa phải nơi quyết định auth cuối cùng.",
        whyItMatters: "Cần nói rõ UI hiện chỉ cho chọn BIDDER/SELLER, nhưng server mới là boundary bảo vệ cuối.",
        failureMode: "Thiếu field hoặc roleBox null làm controller dừng sớm, chưa gửi request.",
        links: [FILE.registerRequest, FILE.clientRequest, FILE.networkClient],
        nextLinks: ["ClientRequest(Action.REGISTER)", "NetworkClient.sendRequestAsync"],
        refPatterns: ["roleBox.setItems", "RegisterRequest", "Action.REGISTER", "sendRequestAsync"],
      }),
      flowStep({
        id: "register-contract",
        order: 3,
        module: "common",
        badge: "Protocol",
        title: "ClientRequest + RegisterRequest là contract chung",
        summary: "Contract nói rõ payload nào đi cùng REGISTER và field nào hai phía phải cùng hiểu.",
        path: FILE.clientRequest,
        role: "Common contract",
        trigger: "Controller chuẩn bị gửi request qua socket.",
        input: "Action.REGISTER + RegisterRequest(username, password, email, role)",
        output: "Object Serializable hợp lệ cho server đọc",
        meaning: "Luồng register chỉ compile/chạy ổn khi client và server cùng dùng chung class trong auction-common.",
        whyItMatters: "Đây là điểm giảng viên hay hỏi khi muốn chứng minh không có duplicate DTO giữa hai phía.",
        failureMode: "Field mismatch hoặc class không Serializable sẽ làm socket deserialize fail.",
        links: [FILE.registerRequest, FILE.actionEnum, FILE.authContractDoc],
        nextLinks: ["ClientHandler.handleIncomingRequest"],
        refPatterns: ["Action action", "Serializable payload", "Generic request wrapper"],
      }),
      flowStep({
        id: "register-handler",
        order: 4,
        module: "server",
        badge: "Socket",
        title: "ClientHandler route REGISTER sang UserService",
        summary: "Server ép kiểu payload và chỉ gọi signup khi request thật sự là RegisterRequest.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "ObjectInputStream đọc xong ClientRequest từ client.",
        input: "ClientRequest(Action.REGISTER, RegisterRequest)",
        output: "ClientResponse từ executeAuthAction(UserService.signup)",
        meaning: "Handler chịu trách nhiệm boundary contract: invalid format/payload sẽ fail ngay ở đây.",
        whyItMatters: "Nói được bước này giúp phân biệt lỗi deserialize/payload với lỗi business trong service.",
        failureMode: "Payload không phải RegisterRequest hoặc action null thì trả failure ngay.",
        links: [FILE.userService, FILE.clientResponse],
        nextLinks: ["UserService.signup"],
        refPatterns: ["case REGISTER", "handleRegister", "RegisterRequest", "executeAuthAction"],
      }),
      flowStep({
        id: "register-service",
        order: 5,
        module: "server",
        badge: "Service",
        title: "UserService.signup validate email/password và hash",
        summary: "Service check duplicate username, regex email/password rồi BCrypt.hashpw trước khi save user.",
        path: FILE.userService,
        role: "Auth service",
        trigger: "ClientHandler đã xác nhận payload hợp lệ.",
        input: "RegisterRequest",
        output: "ClientResponse(success, message, AuthUserData)",
        meaning: "Business rule auth thật sự sống ở server service chứ không nằm trong JavaFX controller.",
        whyItMatters: "Cũng tại đây có drift tiềm năng: source hiện vẫn có branch ADMIN trong switch role.",
        failureMode: "Username trùng, email sai, password yếu hoặc role bất thường đều bị reject ở đây.",
        links: [FILE.serializableUserRepository, FILE.registrationPolicy, FILE.userServiceTest],
        nextLinks: ["SerializableUserRepository.save", "ClientResponse về UI"],
        refPatterns: ["BCrypt.hashpw", "findByUsername", "Username is taken", "switch (userRole)"],
      }),
    ],
  },
  {
    id: "login",
    label: "LOGIN",
    title: "LOGIN: async request, AuthUserData và route theo role",
    subtitle: "Luồng này phải nói rõ client gửi raw credential, server check BCrypt và client chỉ route sau khi nhận AuthUserData.",
    steps: [
      flowStep({
        id: "login-view",
        order: 1,
        module: "client",
        badge: "UI",
        title: "login.fxml gọi handleLogin",
        summary: "View bind username/password input và hành động Login/Register.",
        path: FILE.loginView,
        role: "JavaFX view",
        trigger: "Người dùng đang ở màn login.",
        input: "username + password",
        output: "onAction sang LoginController.handleLogin",
        meaning: "FXML chỉ định đúng controller và action, giúp trace flow từ click đầu tiên.",
        links: [FILE.loginController],
        nextLinks: ["LoginController.handleLogin"],
        refPatterns: ["fx:controller", "handleLogin", "handleRegister"],
      }),
      flowStep({
        id: "login-controller",
        order: 2,
        module: "client",
        badge: "UI",
        title: "LoginController kích hoạt loginAsync",
        summary: "Controller connect socket, hiển thị trạng thái chờ và gọi NetworkClient.loginAsync.",
        path: FILE.loginController,
        role: "JavaFX controller",
        trigger: "User bấm Login.",
        input: "usernameField + passwordField",
        output: "CompletableFuture<ClientResponse>",
        meaning: "Luồng auth ở client được làm async để không block JavaFX thread.",
        whyItMatters: "AuthUserData chỉ được set sau response success, rồi controller mới route sang màn đúng role.",
        failureMode: "Server chết hoặc credential sai thì errorLabel phải đổi message thay vì crash UI.",
        links: [FILE.networkClient, FILE.clientResponse],
        nextLinks: ["NetworkClient.loginAsync", "Platform.runLater route theo role"],
        refPatterns: ["handleLogin", "client.connect", "loginAsync", "AuthUserData", "FXMLLoader.load"],
      }),
      flowStep({
        id: "login-network",
        order: 3,
        module: "client",
        badge: "Socket",
        title: "NetworkClient dùng listener thread + queue",
        summary: "Một socket phục vụ cả ClientResponse lẫn ServerPushMessage nên listener phải phân loại object nhận được.",
        path: FILE.networkClient,
        role: "Client network layer",
        trigger: "LoginController gọi loginAsync hoặc sendRequestAsync.",
        input: "ClientRequest(Action.LOGIN, LoginRequest)",
        output: "ClientResponse được queue lại cho thread đang chờ",
        meaning: "Đây là lời giải cho việc request/response và realtime push đi chung một ObjectInputStream.",
        whyItMatters: "Nếu không nói điểm này, phần realtime rất dễ bị hiểu sai thành polling hoặc socket riêng.",
        failureMode: "Listener thread dừng thì cả login response lẫn push message đều không tới được UI.",
        links: [FILE.clientRequest, FILE.clientResponse, FILE.serverPushMessage],
        nextLinks: ["ClientHandler.handleLogin"],
        refPatterns: ["BlockingQueue<ClientResponse>", "listenForServerMessages", "responseQueue.put", "pushListeners"],
      }),
      flowStep({
        id: "login-handler",
        order: 4,
        module: "server",
        badge: "Socket",
        title: "ClientHandler nhận Action.LOGIN",
        summary: "Server boundary kiểm tra payload có phải LoginRequest trước khi gọi UserService.login.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "ObjectInputStream ở server đọc được ClientRequest.",
        input: "Action.LOGIN + LoginRequest(username, password)",
        output: "ClientResponse chứa AuthUserData hoặc error",
        meaning: "Socket layer không tự hash/check password; nó chỉ xác nhận contract rồi dispatch đúng service.",
        failureMode: "Payload sai kiểu hoặc action null trả failure trước khi chạm repository.",
        links: [FILE.userService, FILE.loginRequest],
        nextLinks: ["UserService.login"],
        refPatterns: ["case LOGIN", "handleLogin", "LOGIN payload must be LoginRequest"],
      }),
      flowStep({
        id: "login-service",
        order: 5,
        module: "server",
        badge: "Service",
        title: "UserService.login check BCrypt và banned state",
        summary: "Server tìm user, BCrypt.checkpw và chặn user bị banned trước khi trả AuthUserData.",
        path: FILE.userService,
        role: "Auth service",
        trigger: "ClientHandler chuyển request login hợp lệ sang service.",
        input: "LoginRequest",
        output: "ClientResponse(success, message, AuthUserData)",
        meaning: "Nơi quyết định auth thật sự vẫn là server; client chỉ phản ánh kết quả.",
        failureMode: "Sai password hoặc user banned đều hiển thị thành failure message cho UI.",
        links: [FILE.serializableUserRepository, FILE.dataStore, FILE.userServiceTest],
        nextLinks: ["ClientResponse -> LoginController route theo role"],
        refPatterns: ["BCrypt.checkpw", "findByUsername", "isBanned", "Login successfully"],
      }),
    ],
  },
  {
    id: "create-item",
    label: "CREATE_ITEM",
    title: "CREATE_ITEM: seller tạo item và server tự sinh auction",
    subtitle: "Điểm quan trọng là ItemFactory chọn subtype và ItemService nối luôn sang scheduler.",
    steps: [
      flowStep({
        id: "create-item-view",
        order: 1,
        module: "client",
        badge: "UI",
        title: "create_item.fxml thu thập thông tin item",
        summary: "View expose thao tác chọn ảnh, nhập giá, loại và thời lượng đấu giá.",
        path: FILE.createItemView,
        role: "JavaFX view",
        trigger: "Seller mở màn tạo item.",
        input: "Tên, mô tả, giá, loại, thời lượng, ảnh",
        output: "onAction sang CreateItemController",
        meaning: "UI này phản ánh đúng yêu cầu dữ liệu cho CreateItemRequest và extraAttributes.",
        links: [FILE.createItemController],
        nextLinks: ["CreateItemController.handleCreateItem"],
        refPatterns: ["fx:controller", "handleCreateItem", "handleChooseImage", "goBack"],
      }),
      flowStep({
        id: "create-item-controller",
        order: 2,
        module: "client",
        badge: "UI",
        title: "CreateItemController đóng gói extraAttributes",
        summary: "Controller parse price/duration, lấy current user và tạo CreateItemRequest với durationMinutes/imagePath.",
        path: FILE.createItemController,
        role: "JavaFX controller",
        trigger: "User bấm tạo item sau khi điền form.",
        input: "Form field + current AuthUserData",
        output: "ClientRequest(Action.CREATE_ITEM, CreateItemRequest)",
        meaning: "Đây là bước chứng minh UI không đụng trực tiếp repository hay scheduler.",
        failureMode: "Sai số ở price/duration hoặc mất currentUser làm flow dừng ở client.",
        links: [FILE.createItemRequest, FILE.clientRequest, FILE.networkClient],
        nextLinks: ["ClientHandler.handleCreateItem"],
        refPatterns: ["durationMinutes", "imagePath", "CreateItemRequest", "Action.CREATE_ITEM"],
      }),
      flowStep({
        id: "create-item-contract",
        order: 3,
        module: "common",
        badge: "Protocol",
        title: "CreateItemRequest mang dữ liệu domain tối thiểu",
        summary: "Contract common gom thông tin item, sellerId, ItemType và extraAttributes để server xử lý một lần.",
        path: FILE.createItemRequest,
        role: "Common message",
        trigger: "Client chuẩn bị gửi Action.CREATE_ITEM.",
        input: "name, description, startingPrice, sellerId, itemType, extraAttributes",
        output: "Serializable payload dùng chung cho client-server",
        meaning: "Giúp tránh duplicate DTO và cho phép ItemService đọc đúng cấu trúc dữ liệu từ socket.",
        links: [FILE.itemEntity, FILE.itemFactory, FILE.authContractDoc],
        nextLinks: ["ClientHandler.handleCreateItem", "ItemService.C"],
        refPatterns: ["CreateItemRequest", "extraAttributes", "sellerId", "itemType"],
      }),
      flowStep({
        id: "create-item-handler",
        order: 4,
        module: "server",
        badge: "Socket",
        title: "ClientHandler xác nhận payload CREATE_ITEM",
        summary: "Handler chỉ chấp nhận CreateItemRequest rồi route sang ItemService.C.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận Action.CREATE_ITEM.",
        input: "ClientRequest(Action.CREATE_ITEM, CreateItemRequest)",
        output: "ClientResponse thành công hoặc lỗi validation",
        meaning: "Tách boundary contract khỏi business rule tạo item/auction.",
        links: [FILE.itemService],
        nextLinks: ["ItemService.C"],
        refPatterns: ["case CREATE_ITEM", "handleCreateItem", "CreateItemRequest"],
      }),
      flowStep({
        id: "create-item-service",
        order: 5,
        module: "server",
        badge: "Service",
        title: "ItemService tạo Item bằng ItemFactory",
        summary: "Service validate input, gọi ItemFactory.createItem, set field theo subtype rồi lưu qua repository.",
        path: FILE.itemService,
        role: "Item service",
        trigger: "Payload hợp lệ đã tới server service.",
        input: "CreateItemRequest",
        output: "Item đã save trong SerializableItemRepository",
        meaning: "Factory pattern xuất hiện ở đây vì controller không tự biết phải new Electronics/Art/Vehicle.",
        whyItMatters: "Phần extraAttributes minh họa rõ cách subtype-specific field được map ở server thay vì UI.",
        failureMode: "Tên trống, giá <= 0, thiếu sellerId hoặc ItemType null đều fail trong service.",
        links: [FILE.itemFactory, FILE.serializableItemRepository, FILE.itemServiceTest],
        nextLinks: ["SerializableItemRepository.save", "AuctionScheduler.scheduleAuctionStart"],
        refPatterns: ["ItemFactory.createItem", "sir.save", "scheduleAuctionStart", "scheduleAuctionEndAt"],
      }),
      flowStep({
        id: "create-item-scheduler",
        order: 6,
        module: "server",
        badge: "Realtime",
        title: "Server tự tạo auction và lên lịch lifecycle",
        summary: "Ngay sau khi item được save, server tạo Auction OPEN, set start/end rồi gọi AuctionScheduler.",
        path: FILE.auctionScheduler,
        role: "Scheduler service",
        trigger: "ItemService đã có Auction mới với startTime/endTime.",
        input: "auctionId + LocalDateTime start/end",
        output: "Scheduled task cho OPEN -> RUNNING -> FINISHED",
        meaning: "Đây là lý do create item hiện tại cũng đồng thời là create auction trong nhánh source này.",
        failureMode: "Sai endTime hoặc scheduler không chạy làm auction không bao giờ start/finish đúng kỳ vọng.",
        links: [FILE.auctionService, FILE.serializableAuctionRepository, FILE.auctionSchedulerTest],
        nextLinks: ["AuctionDetail/AuctionList đọc status từ repository"],
        refPatterns: ["scheduleAuctionStart", "scheduleAuctionEndAt", "finishAuctionNow", "startAuctionNow"],
      }),
    ],
  },
  {
    id: "create-auction",
    label: "CREATE_AUCTION",
    title: "CREATE_AUCTION: contract tách riêng vẫn tồn tại trên server",
    subtitle: "Dù UI seller hiện chủ yếu đi theo CREATE_ITEM, source vẫn có flow CREATE_AUCTION riêng cần hiểu khi bị hỏi về contract.",
    steps: [
      flowStep({
        id: "create-auction-contract",
        order: 1,
        module: "common",
        badge: "Protocol",
        title: "CreateAuctionRequest định nghĩa itemId/startTime/endTime",
        summary: "Contract tách riêng để tạo auction trực tiếp từ item đã tồn tại.",
        path: FILE.createAuctionRequest,
        role: "Common message",
        trigger: "Client hoặc integration test chọn Action.CREATE_AUCTION.",
        input: "itemId + startTime + endTime",
        output: "Serializable payload cho server",
        meaning: "Cho thấy source có cả explicit CREATE_AUCTION bên cạnh path auto-create trong ItemService.",
        links: [FILE.actionEnum, FILE.clientRequest],
        nextLinks: ["ClientHandler.handleCreateAuction"],
        refPatterns: ["CreateAuctionRequest"],
      }),
      flowStep({
        id: "create-auction-handler",
        order: 2,
        module: "server",
        badge: "Socket",
        title: "ClientHandler route CREATE_AUCTION",
        summary: "Boundary kiểm tra payload rồi gọi AuctionService.createAuction.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận Action.CREATE_AUCTION.",
        input: "CreateAuctionRequest",
        output: "ClientResponse chứa Auction mới hoặc lỗi validation",
        meaning: "Luồng explicit create auction bám cùng cơ chế request/response như các action khác.",
        links: [FILE.auctionService],
        nextLinks: ["AuctionService.createAuction"],
        refPatterns: ["case CREATE_AUCTION", "handleCreateAuction"],
      }),
      flowStep({
        id: "create-auction-service",
        order: 3,
        module: "server",
        badge: "Service",
        title: "AuctionService validate item và active auction",
        summary: "Service kiểm tra item có tồn tại, chưa có auction active và endTime phải sau startTime.",
        path: FILE.auctionService,
        role: "Auction service",
        trigger: "Handler đã xác nhận payload hợp lệ.",
        input: "CreateAuctionRequest",
        output: "Auction OPEN đã save vào repository",
        meaning: "Business rule create auction không nằm trong UI hay repository.",
        failureMode: "Item không tồn tại, auction active rồi hoặc endTime <= startTime đều bị reject.",
        links: [FILE.serializableAuctionRepository, FILE.serializableItemRepository, FILE.auctionServiceTest],
        nextLinks: ["AuctionScheduler.scheduleAuctionStart", "AuctionScheduler.scheduleAuctionEndAt"],
        refPatterns: ["already has an active auction", "scheduleAuctionStart", "scheduleAuctionEndAt"],
      }),
    ],
  },
  {
    id: "browse-auctions",
    label: "GET_AUCTIONS",
    title: "GET_AUCTIONS / GET_AUCTION: browse list và mở detail",
    subtitle: "Luồng này là cầu nối giữa bidder UI, contract truy vấn và entity Auction trả về từ repository.",
    steps: [
      flowStep({
        id: "browse-view",
        order: 1,
        module: "client",
        badge: "UI",
        title: "auction_list.fxml + ListView render list",
        summary: "AuctionListController listen selection change để mở detail của auction được chọn.",
        path: FILE.auctionListController,
        role: "JavaFX controller",
        trigger: "Bidder đã login và đang ở màn list.",
        input: "Danh sách Auction đã hoặc sắp được load",
        output: "Selection -> openDetail(newVal)",
        meaning: "Dù controller hiện khá mỏng, nó vẫn là nơi nối màn list sang detail controller.",
        links: [FILE.auctionListView, FILE.auctionDetailController],
        nextLinks: ["GET_AUCTIONS / GET_AUCTION contract", "AuctionDetailController.setData"],
        refPatterns: ["selectedItemProperty", "openDetail", "handleRefresh"],
      }),
      flowStep({
        id: "browse-contract",
        order: 2,
        module: "common",
        badge: "Protocol",
        title: "GetAuctionsRequest và GET_AUCTION contract",
        summary: "Contract truy vấn list cho phép filter seller/status và truy vấn chi tiết theo auctionId.",
        path: FILE.getAuctionsRequest,
        role: "Common message",
        trigger: "Client muốn load list hoặc chi tiết một auction cụ thể.",
        input: "sellerId/statusFilter hoặc auctionId",
        output: "Request có thể deserialize ở server",
        meaning: "Nhắc lại đây không phải query param HTTP; nó là object đi trong ClientRequest.",
        links: [FILE.actionEnum, FILE.clientRequest],
        nextLinks: ["ClientHandler.handleGetAuctions", "ClientHandler.handleGetAuction"],
        refPatterns: ["GetAuctionsRequest"],
      }),
      flowStep({
        id: "browse-handler",
        order: 3,
        module: "server",
        badge: "Socket",
        title: "ClientHandler dispatch GET_AUCTIONS / GET_AUCTION",
        summary: "Server route list và detail về AuctionService với payload tương ứng.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận Action.GET_AUCTIONS hoặc Action.GET_AUCTION.",
        input: "GetAuctionsRequest hoặc auctionId(String)",
        output: "ClientResponse với List<Auction> hoặc Auction",
        meaning: "Đây là bước tách contract object và business query.",
        links: [FILE.auctionService, FILE.clientResponse],
        nextLinks: ["AuctionService.getAuctions/getAuction"],
        refPatterns: ["case GET_AUCTIONS", "case GET_AUCTION", "handleGetAuctions", "handleGetAuction"],
      }),
      flowStep({
        id: "browse-service",
        order: 4,
        module: "server",
        badge: "Service",
        title: "AuctionService đọc repository và filter",
        summary: "Service dùng SerializableAuctionRepository để trả list/detail đúng theo seller hoặc status filter.",
        path: FILE.auctionService,
        role: "Auction service",
        trigger: "Handler đã chọn đúng branch GET_AUCTIONS hoặc GET_AUCTION.",
        input: "request filter hoặc auctionId",
        output: "ClientResponse thành công với Serializable auction data",
        meaning: "Phần filter logic ở service giúp controller/client không phải đoán dữ liệu đã bị lọc ở đâu.",
        failureMode: "Auction không tồn tại hoặc repository lỗi sẽ phản ánh thành failure message từ service.",
        links: [FILE.serializableAuctionRepository, FILE.auctionEntity, FILE.auctionServiceTest],
        nextLinks: ["AuctionListController render list", "AuctionDetailController.setData"],
        refPatterns: ["findAll", "findById", "Fetched", "statusFilter"],
      }),
    ],
  },
  {
    id: "place-bid",
    label: "PLACE_BID",
    title: "PLACE_BID: luồng vấn đáp trọng tâm nhất của repo",
    subtitle: "Place bid nối đủ UI, socket, handler, lock, anti-sniping và observer push; đây là flow bắt buộc phải thuộc end-to-end.",
    steps: [
      flowStep({
        id: "bid-view",
        order: 1,
        module: "client",
        badge: "UI",
        title: "AuctionDetailController nhận số tiền bid",
        summary: "Controller validate input, lấy current user và tạo PlaceBidRequest cho manual bid.",
        path: FILE.auctionDetailController,
        role: "JavaFX controller",
        trigger: "Bidder nhập amount và bấm Place Bid.",
        input: "auctionId hiện tại + bidderId từ session + amount",
        output: "ClientRequest(Action.PLACE_BID, PlaceBidRequest)",
        meaning: "UI chỉ đọc input và phản ánh kết quả; nó không tự thay đổi auction state trên client.",
        failureMode: "Amount rỗng hoặc parse lỗi làm controller dừng sớm; currentUser null yêu cầu login lại.",
        links: [FILE.placeBidRequest, FILE.networkClient, FILE.auctionDetailView],
        nextLinks: ["NetworkClient.sendRequestAsync", "ClientHandler.handlePlaceBid"],
        refPatterns: ["handlePlaceBid", "PlaceBidRequest", "Action.PLACE_BID", "sendRequestAsync"],
      }),
      flowStep({
        id: "bid-network",
        order: 2,
        module: "client",
        badge: "Socket",
        title: "NetworkClient gửi request qua ObjectOutputStream",
        summary: "Client không chờ trên JavaFX thread; response quay về qua queue còn push message chạy qua listener.",
        path: FILE.networkClient,
        role: "Client network layer",
        trigger: "AuctionDetailController gọi sendRequestAsync.",
        input: "ClientRequest(Action.PLACE_BID, payload)",
        output: "CompletableFuture<ClientResponse>",
        meaning: "Một kết nối socket xử lý cả response và realtime nên đây là điểm neo quan trọng khi bị hỏi về concurrency ở client.",
        links: [FILE.clientRequest, FILE.clientResponse, FILE.serverPushMessage],
        nextLinks: ["ClientHandler.handleIncomingRequest"],
        refPatterns: ["writeObject", "responseQueue.take", "sendRequestAsync", "listenForServerMessages"],
      }),
      flowStep({
        id: "bid-handler",
        order: 3,
        module: "server",
        badge: "Socket",
        title: "ClientHandler tách manual bid và auto-bid branch",
        summary: "Nếu req.isAutoBid thì tạo AutoBid config; nếu không thì gọi BidService.placeBid với ManualBidStrategy.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận Action.PLACE_BID.",
        input: "PlaceBidRequest",
        output: "ClientResponse thành công hoặc failure message",
        meaning: "Chỗ này nói rõ một action PLACE_BID hiện đang bao cả nhánh auto-bid đơn giản và nhánh manual bid.",
        failureMode: "Payload sai kiểu hoặc auto-bid đã đăng ký rồi sẽ fail ngay ở handler.",
        links: [FILE.bidService, FILE.autoBidService, FILE.manualBidStrategy],
        nextLinks: ["BidService.placeBid", "AutoBidService.registerAutoBid"],
        refPatterns: ["case PLACE_BID", "req.isAutoBid()", "ManualBidStrategy", "AutoBid config"],
      }),
      flowStep({
        id: "bid-service",
        order: 4,
        module: "server",
        badge: "Service",
        title: "BidService giữ ReentrantLock theo auctionId",
        summary: "Service validate auction RUNNING, gọi strategy, update currentPrice/highestBidder và save transaction.",
        path: FILE.bidService,
        role: "Bidding service",
        trigger: "Handler đã chọn nhánh manual bid.",
        input: "auctionId, bidderId, amount, BidStrategy",
        output: "BidTransaction đã save + Auction đã update",
        meaning: "Fine-grained lock là lý do nhiều auction khác nhau vẫn bid song song được mà không lost update trên cùng auction.",
        whyItMatters: "Khi bị hỏi race condition, đây là file phải mở đầu tiên chứ không phải repository.",
        failureMode: "Auction không RUNNING, invalid amount hoặc lock/unlock sai đều phá vỡ invariant currentPrice.",
        links: [FILE.serializableAuctionRepository, FILE.serializableBidRepository, FILE.bidConcurrencyTest, FILE.bidServiceTest],
        nextLinks: ["AuctionScheduler.extendAuctionEnd", "AuctionEventManager.notifyNewBid"],
        refPatterns: ["computeIfAbsent", "lock.lock()", "AuctionStatus.RUNNING", "notifyNewBid"],
      }),
      flowStep({
        id: "bid-anti-sniping",
        order: 5,
        module: "server",
        badge: "Realtime",
        title: "BidService kích anti-sniping qua AuctionScheduler",
        summary: "Bid tới trong 30 giây cuối sẽ dời endTime và reschedule task end để phiên không đóng hụt.",
        path: FILE.auctionScheduler,
        role: "Scheduler service",
        trigger: "BidService phát hiện secondsLeft nằm trong anti-sniping window.",
        input: "auctionId + extraSeconds",
        output: "Auction endTime mới + scheduledEndTasks mới",
        meaning: "Nói được bước này giúp chứng minh dự án có lifecycle động chứ không chỉ countdown tĩnh ở UI.",
        failureMode: "Không cancel task cũ trước khi reschedule sẽ làm end task chạy sai thời điểm.",
        links: [FILE.bidService, FILE.auctionSchedulerTest],
        nextLinks: ["AuctionEventManager/BroadcastObserver push realtime"],
        refPatterns: ["ANTI_SNIPE_WINDOW_SECONDS", "extendAuctionEnd", "scheduleAuctionEndAt"],
      }),
      flowStep({
        id: "bid-observer",
        order: 6,
        module: "server",
        badge: "Realtime",
        title: "Observer phát push NEW_BID/PRICE_UPDATE/AUCTION_ENDED",
        summary: "Sau khi state hợp lệ được lưu, AuctionEventManager gọi BroadcastObserver để broadcast ServerPushMessage.",
        path: FILE.broadcastObserver,
        role: "Realtime observer",
        trigger: "BidService gọi eventManager.notifyNewBid hoặc scheduler đổi trạng thái.",
        input: "Auction + BidTransaction hoặc AuctionStatus change",
        output: "ServerPushMessage tới mọi client đang connect",
        meaning: "Observer pattern tách phần phát thông báo khỏi business service đặt giá.",
        failureMode: "Broadcast trước khi state được update sẽ làm client thấy dữ liệu lệch với repository.",
        links: [FILE.auctionEventManager, FILE.clientRegistry, FILE.serverPushMessage],
        nextLinks: ["AuctionDetailController.registerPushListener"],
        refPatterns: ["onNewBid", "PRICE_UPDATE", "broadcast", "AUCTION_ENDED"],
      }),
      flowStep({
        id: "bid-client-push",
        order: 7,
        module: "client",
        badge: "Realtime",
        title: "AuctionDetailController nhận push và cập nhật UI",
        summary: "PushListener lọc đúng auction đang xem, cập nhật priceLabel/timeLabel và disable input khi phiên kết thúc.",
        path: FILE.auctionDetailController,
        role: "JavaFX controller",
        trigger: "NetworkClient listener dispatch ServerPushMessage về client.",
        input: "NEW_BID hoặc AUCTION_ENDED",
        output: "UI price/time phản ánh state mới trên JavaFX thread",
        meaning: "Đây là chỗ đóng vòng loop realtime từ server về user.",
        failureMode: "Quên remove listener hoặc update UI ngoài Platform.runLater sẽ gây lỗi khó trace.",
        links: [FILE.networkClient, FILE.serverPushMessage],
        nextLinks: ["Bidder thấy state mới và tiếp tục bid hoặc dừng"],
        refPatterns: ["registerPushListener", "PushType.NEW_BID", "PushType.AUCTION_ENDED", "Platform.runLater"],
      }),
    ],
  },
  {
    id: "bid-history",
    label: "GET_BID_HISTORY",
    title: "GET_BID_HISTORY: đọc lịch sử bid từ repository",
    subtitle: "Flow ngắn nhưng hay bị hỏi để phân biệt currentPrice hiện tại với lịch sử transaction.",
    steps: [
      flowStep({
        id: "history-contract",
        order: 1,
        module: "common",
        badge: "Protocol",
        title: "GetBidHistoryRequest mang auctionId",
        summary: "Client phải gửi đúng auctionId để server truy hồi lịch sử bid của một phiên.",
        path: FILE.getBidHistoryRequest,
        role: "Common message",
        trigger: "Client muốn xem lịch sử bid hoặc integration test cần kiểm chứng.",
        input: "auctionId",
        output: "Request Serializable",
        meaning: "Tách current auction view với danh sách BidTransaction lưu riêng trong repository.",
        links: [FILE.placeBidRequest, FILE.clientRequest],
        nextLinks: ["ClientHandler.handleGetBidHistory"],
        refPatterns: ["GetBidHistoryRequest"],
      }),
      flowStep({
        id: "history-handler",
        order: 2,
        module: "server",
        badge: "Socket",
        title: "ClientHandler route GET_BID_HISTORY",
        summary: "Server xác nhận payload đúng kiểu rồi gọi BidService.getBidHistory.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận Action.GET_BID_HISTORY.",
        input: "GetBidHistoryRequest",
        output: "ClientResponse(data = List<BidTransaction>)",
        meaning: "Đây là case đơn giản để chứng minh handler chỉ dispatch chứ không tự đọc repository.",
        links: [FILE.bidService, FILE.clientResponse],
        nextLinks: ["BidService.getBidHistory"],
        refPatterns: ["case GET_BID_HISTORY", "handleGetBidHistory"],
      }),
      flowStep({
        id: "history-service",
        order: 3,
        module: "server",
        badge: "Repository",
        title: "BidService đọc SerializableBidRepository",
        summary: "Service trả lại List<BidTransaction> theo auctionId để client hoặc test hiển thị theo thời gian.",
        path: FILE.bidService,
        role: "Bidding service",
        trigger: "Handler đã xác nhận payload hợp lệ.",
        input: "auctionId",
        output: "List<BidTransaction>",
        meaning: "Lịch sử bid là dữ liệu persistence riêng, không nên suy ngược từ currentPrice hiện tại.",
        failureMode: "Nếu repository lưu sai hoặc không theo auctionId, lịch sử sẽ lệch dù currentPrice có vẻ đúng.",
        links: [FILE.serializableBidRepository, FILE.bidTransactionEntity, FILE.bidServiceTest],
        nextLinks: ["ClientResponse -> UI/test hiển thị timeline"],
        refPatterns: ["getBidHistory", "findByAuctionId"],
      }),
    ],
  },
  {
    id: "auto-bid",
    label: "AUTO_BID",
    title: "REGISTER_AUTO_BID / REMOVE_AUTO_BID",
    subtitle: "Auto-bid vừa là contract riêng vừa là observer flow chạy sau khi có bid mới trên một auction đang RUNNING.",
    steps: [
      flowStep({
        id: "auto-bid-contract",
        order: 1,
        module: "common",
        badge: "Protocol",
        title: "RegisterAutoBidRequest và RemoveAutoBidRequest",
        summary: "Contract tách riêng cho cấu hình auto-bid, không trộn với manual bid history hoặc auth payload.",
        path: FILE.registerAutoBidRequest,
        role: "Common message",
        trigger: "Bidder muốn đăng ký hoặc gỡ auto-bid cho auction đang theo dõi.",
        input: "auctionId, bidderId, maxBid, increment",
        output: "Serializable request cho server",
        meaning: "Dù handler còn hỗ trợ nhánh isAutoBid trong PLACE_BID, source hiện đã có action riêng cho auto-bid cấu hình.",
        links: [FILE.removeAutoBidRequest, FILE.actionEnum, FILE.authContractDoc],
        nextLinks: ["ClientHandler.handleRegisterAutoBid", "ClientHandler.handleRemoveAutoBid"],
        refPatterns: ["RegisterAutoBidRequest"],
      }),
      flowStep({
        id: "auto-bid-handler",
        order: 2,
        module: "server",
        badge: "Socket",
        title: "ClientHandler đăng ký hoặc gỡ config",
        summary: "Handler tạo AutoBid config từ payload rồi gọi AutoBidService.registerAutoBid/removeAutoBid.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận Action.REGISTER_AUTO_BID hoặc REMOVE_AUTO_BID.",
        input: "RegisterAutoBidRequest / RemoveAutoBidRequest",
        output: "ClientResponse message xác nhận",
        meaning: "Đây là bước đặt rule cho auto-bid chứ chưa trực tiếp tạo BidTransaction mới.",
        links: [FILE.autoBidService, FILE.clientResponse],
        nextLinks: ["AutoBidService giữ config", "AutoBidService.onNewBid"],
        refPatterns: ["case REGISTER_AUTO_BID", "case REMOVE_AUTO_BID", "registerAutoBid", "removeAutoBid"],
      }),
      flowStep({
        id: "auto-bid-observer",
        order: 3,
        module: "server",
        badge: "Realtime",
        title: "AutoBidService chờ sự kiện onNewBid",
        summary: "Observer chỉ phản ứng khi auction còn RUNNING, bidder khác vừa bid và maxBid của config vẫn còn hiệu lực.",
        path: FILE.autoBidService,
        role: "Observer service",
        trigger: "AuctionEventManager phát onNewBid sau một bid hợp lệ.",
        input: "Auction + BidTransaction mới",
        output: "Lệnh bid mới qua AutoBidStrategy hoặc deactivate config",
        meaning: "AutoBid không polling; nó hoàn toàn bám event stream của observer.",
        failureMode: "Không lọc bidder trùng hoặc config inactive sẽ tạo vòng lặp bid vô hạn hoặc bid sai người.",
        links: [FILE.autoBidStrategy, FILE.bidService, FILE.broadcastObserver],
        nextLinks: ["BidService.placeBid(strategy=AutoBidStrategy)"],
        refPatterns: ["onNewBid", "hasAutoBid", "AutoBidStrategy", "config.setActive(false)"],
      }),
      flowStep({
        id: "auto-bid-strategy",
        order: 4,
        module: "common",
        badge: "Service",
        title: "AutoBidStrategy tính amount kế tiếp",
        summary: "Strategy tách cách tính bid tự động ra khỏi BidService để service không bị if-else theo mode.",
        path: FILE.autoBidStrategy,
        role: "Common strategy",
        trigger: "AutoBidService quyết định config còn active và auction còn RUNNING.",
        input: "Auction hiện tại + AutoBid config",
        output: "BidTransaction hoặc lỗi InvalidBidException",
        meaning: "Đây là ví dụ rõ nhất cho Strategy Pattern trong repo.",
        links: [FILE.manualBidStrategy, FILE.bidServiceTest],
        nextLinks: ["BidService.placeBid dùng strategy đã inject"],
        refPatterns: ["AutoBidStrategy"],
      }),
    ],
  },
  {
    id: "admin-moderation",
    label: "ADMIN",
    title: "ADMIN BAN / UNBAN / CANCEL_AUCTION",
    subtitle: "Cần nói được boundary permission ở server và tác động dây chuyền sang observer/realtime khi admin hủy phiên.",
    steps: [
      flowStep({
        id: "admin-contract",
        order: 1,
        module: "common",
        badge: "Protocol",
        title: "Các request quản trị dùng common message riêng",
        summary: "GetAllUsersRequest, BanUserRequest, UnbanUserRequest và CancelAuctionRequest giúp tách admin flow khỏi bidder/seller flow.",
        path: FILE.banUserRequest,
        role: "Common message",
        trigger: "Admin thao tác quản trị hoặc integration test kiểm tra permission boundary.",
        input: "adminId + targetUserId/auctionId + reason",
        output: "Serializable payload cho server",
        meaning: "Request quản trị cần nói rõ adminId, vì server không tin vào UI badge hay màn hiện tại.",
        links: [FILE.getAllUsersRequest, FILE.unbanUserRequest, FILE.cancelAuctionRequest],
        nextLinks: ["ClientHandler route admin actions"],
        refPatterns: ["BanUserRequest"],
      }),
      flowStep({
        id: "admin-handler",
        order: 2,
        module: "server",
        badge: "Socket",
        title: "ClientHandler dispatch GET_USERS / BAN_USER / UNBAN_USER / CANCEL_AUCTION",
        summary: "Boundary ép kiểu payload rồi gọi đúng UserService hoặc AuctionService branch.",
        path: FILE.clientHandler,
        role: "Socket boundary",
        trigger: "Server nhận admin action.",
        input: "Admin request payload",
        output: "ClientResponse phù hợp cho từng action",
        meaning: "Đây là điểm chứng minh permission không nằm ở admin.fxml mà nằm ở nhánh server.",
        links: [FILE.userService, FILE.auctionService],
        nextLinks: ["UserService.banUser/unbanUser", "AuctionService.cancelAuction"],
        refPatterns: ["case GET_USERS", "case BAN_USER", "case UNBAN_USER", "case CANCEL_AUCTION"],
      }),
      flowStep({
        id: "admin-user-service",
        order: 3,
        module: "server",
        badge: "Service",
        title: "UserService kiểm tra UserRole.ADMIN rồi update repository",
        summary: "Service ban/unban chỉ cho admin thực sự và không cho ban một admin khác.",
        path: FILE.userService,
        role: "Auth/admin service",
        trigger: "Handler đã xác nhận payload đúng kiểu.",
        input: "BanUserRequest / UnbanUserRequest",
        output: "ClientResponse + user state update",
        meaning: "Đây là permission boundary cuối cùng cho admin user management.",
        failureMode: "adminId không phải ADMIN hoặc target user null sẽ fail tại đây.",
        links: [FILE.serializableUserRepository, FILE.userRole, FILE.userServiceTest],
        nextLinks: ["ClientResponse -> admin UI/test"],
        refPatterns: ["ADMIN PERM", "Cannot ban an admin", "sur.update"],
      }),
      flowStep({
        id: "admin-auction-service",
        order: 4,
        module: "server",
        badge: "Realtime",
        title: "AuctionService.cancelAuction đổi status và notify observer",
        summary: "Admin cancel không chỉ update status CANCELED mà còn phát notifyStatusChanged + notifyAuctionEnded.",
        path: FILE.auctionService,
        role: "Auction service",
        trigger: "Handler gọi cancelAuction với adminId và reason.",
        input: "CancelAuctionRequest",
        output: "Auction CANCELED + realtime push cho client đang xem",
        meaning: "Nếu không nói observer ở bước này, câu trả lời cancel auction sẽ thiếu mất phần side effect realtime.",
        failureMode: "Auction đã FINISHED/CANCELED hoặc adminId không hợp lệ đều bị reject.",
        links: [FILE.broadcastObserver, FILE.auctionEventManager, FILE.auctionServiceTest],
        nextLinks: ["BroadcastObserver push AUCTION_ENDED", "AutoBidService clear config"],
        refPatterns: ["cancelAuction", "AuctionStatus.CANCELED", "notifyAuctionEnded"],
      }),
    ],
  },
  {
    id: "scheduler",
    label: "SCHEDULER",
    title: "AUCTION SCHEDULER / close auction / realtime end-state",
    subtitle: "Flow này gom lifecycle OPEN -> RUNNING -> FINISHED, anti-sniping reschedule và persistence snapshot.",
    steps: [
      flowStep({
        id: "scheduler-start",
        order: 1,
        module: "server",
        badge: "Service",
        title: "AuctionScheduler giữ ScheduledFuture theo auctionId",
        summary: "Server schedule start/end task, hoặc chạy ngay nếu thời gian đã tới.",
        path: FILE.auctionScheduler,
        role: "Scheduler service",
        trigger: "Create item hoặc create auction thành công.",
        input: "auctionId + startTime/endTime",
        output: "Scheduled task trong scheduledEndTasks",
        meaning: "Lifecycle auction là server-side, không phụ thuộc tab client còn mở hay không.",
        failureMode: "Schedule sai delay hoặc bỏ map auctionId -> future sẽ làm extend/cancel task không chính xác.",
        links: [FILE.itemService, FILE.auctionService, FILE.auctionSchedulerTest],
        nextLinks: ["AuctionStatus.OPEN -> RUNNING", "AuctionStatus.RUNNING -> FINISHED"],
        refPatterns: ["scheduleAuctionStart", "scheduleAuctionEnd", "scheduledEndTasks"],
      }),
      flowStep({
        id: "scheduler-status-change",
        order: 2,
        module: "server",
        badge: "Realtime",
        title: "startAuctionNow / finishAuctionNow cập nhật status",
        summary: "Scheduler update repository rồi phát notifyStatusChanged/notifyAuctionEnded thông qua event manager.",
        path: FILE.auctionScheduler,
        role: "Scheduler service",
        trigger: "Task start/end tới hạn hoặc anti-sniping reschedule xong.",
        input: "auctionId đã đến mốc start/end",
        output: "AuctionStatus RUNNING hoặc FINISHED + broadcast side effects",
        meaning: "Đây là đoạn nối lifecycle với realtime thay vì chỉ đổi field status trong repository.",
        failureMode: "Không notify observer sau update sẽ làm client không biết phiên đã bắt đầu hoặc kết thúc.",
        links: [FILE.broadcastObserver, FILE.auctionEventManager],
        nextLinks: ["BroadcastObserver push AUCTION_STARTED/AUCTION_ENDED"],
        refPatterns: ["startAuctionNow", "finishAuctionNow", "notifyStatusChanged", "notifyAuctionEnded"],
      }),
      flowStep({
        id: "scheduler-persistence",
        order: 3,
        module: "server",
        badge: "Repository",
        title: "DataStore giữ snapshot auction_data.dat",
        summary: "Mọi thay đổi qua repository cuối cùng đều đi về DataStore và được save/load bằng serialization.",
        path: FILE.dataStore,
        role: "Persistence root",
        trigger: "Server startup/shutdown hoặc repository save/update.",
        input: "users, items, auctions, bidTransactions trong RAM",
        output: "File data/auction_data.dat + default admin bootstrap khi cần",
        meaning: "Bị hỏi 'dữ liệu nằm đâu' thì phải mở DataStore, không được trả lời bằng database server tưởng tượng.",
        failureMode: "File hỏng hoặc save/load lỗi sẽ làm server mất state dù logic service đúng.",
        links: [FILE.serializableAuctionRepository, FILE.serializableBidRepository, FILE.repositoryTest],
        nextLinks: ["Server restart vẫn nạp lại snapshot"],
        refPatterns: ["FILE_PATH", "loadData", "saveData", "ensureDefaultAdminAccount"],
      }),
    ],
  },
];

export const lifecycleStates = [
  { name: "OPEN", note: "Auction vừa được tạo, scheduler đang chờ tới thời điểm start." },
  { name: "RUNNING", note: "Phiên đang cho phép place bid; anti-sniping có thể kéo dài endTime." },
  { name: "FINISHED", note: "Scheduler đã đóng phiên và observer đã phát push AUCTION_ENDED." },
  { name: "CANCELED", note: "Admin đã hủy phiên; client cần thấy trạng thái kết thúc và dừng bid." },
];

export const dbTables = [
  {
    name: "users[]",
    color: "#3157d5",
    columns: ["id", "username", "passwordHash", "email", "role", "banned", "banReason"],
  },
  {
    name: "items[]",
    color: "#0f766e",
    columns: ["id", "sellerId", "itemType", "name", "description", "startingPrice", "extra subtype fields"],
  },
  {
    name: "auctions[]",
    color: "#ea580c",
    columns: ["id", "itemId", "sellerId", "status", "startTime", "endTime", "currentPrice", "highestBidderId"],
  },
  {
    name: "bidTransactions[]",
    color: "#7c3aed",
    columns: ["id", "auctionId", "bidderId", "bidAmount", "timestamp", "strategy result"],
  },
];

export const mavenModules = [
  {
    name: "root build",
    purpose: "Parent reactor ghép toàn dự án, giúp build và test đồng bộ toàn bộ shared contract + server + client.",
    deps: ["auction-common", "auction-server", "auction-client", "mvnw / mvnw.cmd"],
  },
  {
    name: "auction-common",
    purpose: "Chứa entity, enum, message contract và các pattern dùng chung cho cả client lẫn server.",
    deps: ["Action", "ClientRequest", "ClientResponse", "Factory", "Strategy", "Observer Contract"],
  },
  {
    name: "auction-server",
    purpose: "Socket server, handler, service, repository, DataStore và scheduler/realtime observer.",
    deps: ["auction-common", "BCrypt", "Serializable repositories", "ScheduledExecutorService"],
  },
  {
    name: "auction-client",
    purpose: "JavaFX UI, controller, NetworkClient và FXML view để người dùng cuối tương tác với server.",
    deps: ["auction-common", "JavaFX 17", "NetworkClient", "FXML view"],
  },
];

export const theoryTopics: StudyTopic[] = [
  {
    id: "client-server-boundary",
    title: "Client-server boundary",
    category: "Architecture & Contracts",
    level: "Core",
    status: "done",
    summary: "Phân biệt rõ UI/controller/client socket với handler/service/repository ở server để không trả lời lẫn trách nhiệm.",
    projectExample: "LoginController chỉ gọi NetworkClient; ClientHandler mới là nơi route Action.LOGIN sang UserService.login.",
    files: [FILE.loginController, FILE.networkClient, FILE.clientHandler, FILE.architectureDoc],
    links: [
      { label: "Project Architecture Deep Dive", url: "https://docs.oracle.com/en/java/javase/17/docs/api/" },
      { label: "Socket Overview", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/Socket.html" },
    ],
  },
  {
    id: "serialization-contract",
    title: "Java Serialization contract",
    category: "Architecture & Contracts",
    level: "Core",
    status: "done",
    summary: "Raw TCP socket của repo này truyền object Serializable, nên cả client lẫn server phải cùng dùng class trong auction-common.",
    projectExample: "NetworkClient dùng ObjectOutputStream/ObjectInputStream; ClientRequest và ClientResponse là contract chung.",
    files: [FILE.clientRequest, FILE.clientResponse, FILE.networkClient, FILE.runServerDoc],
    links: [
      { label: "ObjectOutputStream", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/ObjectOutputStream.html" },
      { label: "ObjectInputStream", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/ObjectInputStream.html" },
    ],
  },
  {
    id: "maven-reactor",
    title: "Maven multi-module reactor",
    category: "Architecture & Contracts",
    level: "Core",
    status: "done",
    summary: "Parent pom giúp giữ shared contract compile chung với server và client, giảm drift khi message/entity thay đổi.",
    projectExample: "auction-common là source of truth cho Action, Request/Response, entity và pattern interfaces.",
    files: [FILE.rootPom, FILE.readme],
    links: [
      { label: "Maven Reactor", url: "https://maven.apache.org/guides/mini/guide-multiple-modules.html" },
      { label: "README Build Guide", url: "https://maven.apache.org/wrapper/" },
    ],
  },
  {
    id: "repository-pattern",
    title: "Repository pattern trên DataStore",
    category: "Design Principles & Patterns",
    level: "Deep dive",
    status: "review",
    summary: "Service không động vào list trong DataStore trực tiếp mà đi qua repository để cô lập persistence và test dễ hơn.",
    projectExample: "BidService dùng AuctionRepository/BidRepository, còn UserService dùng SerializableUserRepository.",
    files: [FILE.serializableAuctionRepository, FILE.serializableBidRepository, FILE.serializableUserRepository, FILE.dataStore],
    links: [
      { label: "Repository Pattern", url: "https://martinfowler.com/eaaCatalog/repository.html" },
      { label: "DataStore Source", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/Serializable.html" },
    ],
  },
  {
    id: "factory-pattern",
    title: "Factory pattern cho Item subtype",
    category: "Design Principles & Patterns",
    level: "Core",
    status: "done",
    summary: "Factory giúp chọn đúng subclass item theo ItemType mà không để UI/service new thủ công từng loại.",
    projectExample: "ItemService.C gọi ItemFactory.createItem rồi map extraAttributes vào Electronics/Art/Vehicle.",
    files: [FILE.itemFactory, FILE.itemService, FILE.itemServiceTest],
    links: [
      { label: "Factory Method", url: "https://refactoring.guru/design-patterns/factory-method" },
      { label: "Item Factory Test", url: "https://junit.org/junit5/" },
    ],
  },
  {
    id: "strategy-pattern",
    title: "Strategy pattern cho bidding",
    category: "Design Principles & Patterns",
    level: "Deep dive",
    status: "done",
    summary: "ManualBidStrategy và AutoBidStrategy cho phép BidService giữ một pipeline chung nhưng thay đổi cách tính bid.",
    projectExample: "ClientHandler inject ManualBidStrategy cho manual bid; AutoBidService inject AutoBidStrategy khi observer kích hoạt.",
    files: [FILE.manualBidStrategy, FILE.autoBidStrategy, FILE.bidService],
    links: [
      { label: "Strategy Pattern", url: "https://refactoring.guru/design-patterns/strategy" },
      { label: "BidService", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html" },
    ],
  },
  {
    id: "observer-pattern",
    title: "Observer pattern và realtime push",
    category: "Design Principles & Patterns",
    level: "Deep dive",
    status: "done",
    summary: "AuctionEventManager publish event, BroadcastObserver và AutoBidService subscribe để push UI hoặc tự đặt giá.",
    projectExample: "Một bid hợp lệ đi qua BidService rồi notifyNewBid; observer mới broadcast hoặc auto-place bid.",
    files: [FILE.auctionEventManager, FILE.broadcastObserver, FILE.autoBidService, FILE.auctionDetailController],
    links: [
      { label: "Observer Pattern", url: "https://refactoring.guru/design-patterns/observer" },
      { label: "JavaFX Threading", url: "https://openjfx.io/javadoc/17/javafx.graphics/javafx/application/Platform.html" },
    ],
  },
  {
    id: "scheduler-anti-sniping",
    title: "Scheduler và anti-sniping",
    category: "Concurrency, Realtime & Persistence",
    level: "Deep dive",
    status: "review",
    summary: "Scheduler giữ task start/end; BidService có thể gọi extendAuctionEnd khi bid đến sát giờ đóng phiên.",
    projectExample: "AuctionScheduler.scheduleAuctionEndAt + extendAuctionEnd là cặp hàm trọng tâm của lifecycle động.",
    files: [FILE.auctionScheduler, FILE.bidService, FILE.auctionSchedulerTest],
    links: [
      { label: "ScheduledExecutorService", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ScheduledExecutorService.html" },
      { label: "Auction Scheduler Test", url: "https://junit.org/junit5/" },
    ],
  },
  {
    id: "bcrypt-auth",
    title: "BCrypt và auth server-side",
    category: "Concurrency, Realtime & Persistence",
    level: "Core",
    status: "done",
    summary: "Password được hash/check ở server để client không được xem là nguồn sự thật cho auth.",
    projectExample: "UserService.signup hash password; UserService.login dùng BCrypt.checkpw và kiểm tra banned state.",
    files: [FILE.userService, FILE.userServiceTest, FILE.authContractDoc],
    links: [
      { label: "jBCrypt", url: "https://www.mindrot.org/projects/jBCrypt/" },
      { label: "OWASP Password Storage", url: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html" },
    ],
  },
  {
    id: "per-auction-lock",
    title: "Fine-grained lock theo auctionId",
    category: "Concurrency, Realtime & Persistence",
    level: "Deep dive",
    status: "risk",
    summary: "Lock theo auctionId bảo vệ currentPrice/highestBidder trên cùng phiên nhưng vẫn cho auction khác chạy song song.",
    projectExample: "BidService giữ ConcurrentHashMap<String, ReentrantLock> và computeIfAbsent khi placeBid.",
    files: [FILE.bidService, FILE.bidConcurrencyTest],
    links: [
      { label: "ReentrantLock", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html" },
      { label: "ConcurrentHashMap", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html" },
    ],
  },
  {
    id: "datastore-persistence",
    title: "Persistence snapshot qua auction_data.dat",
    category: "Concurrency, Realtime & Persistence",
    level: "Core",
    status: "review",
    summary: "DataStore là singleton in-memory nhưng có save/load snapshot ra file `.dat`, nên câu trả lời về dữ liệu phải bám source này.",
    projectExample: "DataStore.loadData/saveData và ensureDefaultAdminAccount giải quyết cả bootstrap lẫn persistence.",
    files: [FILE.dataStore, FILE.repositoryTest, FILE.runServerDoc],
    links: [
      { label: "Serializable", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/Serializable.html" },
      { label: "Java File I/O", url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/package-summary.html" },
    ],
  },
  {
    id: "tests-as-proof",
    title: "Đọc test như bằng chứng bảo vệ behavior",
    category: "Testing & Delivery",
    level: "Core",
    status: "done",
    summary: "Unit test và integration test trong repo giúp chứng minh auth, item flow, scheduler và concurrency bằng code thực thi được.",
    projectExample: "BidServiceConcurrencyTest, AuctionSchedulerTest, UserServiceTest và AuctionE2ETest là bốn file nên thuộc.",
    files: [FILE.bidConcurrencyTest, FILE.auctionSchedulerTest, FILE.userServiceTest, FILE.auctionE2eTest],
    links: [
      { label: "JUnit 5", url: "https://junit.org/junit5/" },
      { label: "Maven Surefire", url: "https://maven.apache.org/surefire/maven-surefire-plugin/" },
    ],
  },
];

export const testCases: TestCase[] = [
  {
    name: "UserServiceTest",
    target: "Bảo vệ đăng ký/đăng nhập: duplicate username, password policy, BCrypt check và banned user path.",
    command: ".\\mvnw.cmd -pl auction-server -Dtest=UserServiceTest test",
    arrange: "Tạo input RegisterRequest/LoginRequest và seed repository hoặc DataStore state tối thiểu.",
    act: "Gọi signup/login qua service hoặc branch test tương ứng.",
    assert: "Kiểm tra ClientResponse success/failure và dữ liệu auth trả về đúng với rule của source.",
    viva: "Nếu bị hỏi auth sống ở đâu, mở UserServiceTest rồi nối lại tới BCrypt trong UserService.",
  },
  {
    name: "ItemServiceTest",
    target: "Bảo vệ flow create item, map extraAttributes và tự tạo auction + schedule sau khi save item.",
    command: ".\\mvnw.cmd -pl auction-server -Dtest=ItemServiceTest test",
    arrange: "Chuẩn bị CreateItemRequest với itemType, sellerId và extraAttributes hợp lệ.",
    act: "Gọi ItemService.C hoặc update/delete branch tương ứng.",
    assert: "Item được tạo đúng subtype, repository update đúng và auction liên kết được sinh ra như kỳ vọng.",
    viva: "Đây là test tốt để chứng minh Factory Pattern không chỉ là lý thuyết mà đã chạy trong source.",
  },
  {
    name: "AuctionServiceTest",
    target: "Bảo vệ create/get/cancel auction và các validation như active auction hay endTime không hợp lệ.",
    command: ".\\mvnw.cmd -pl auction-server -Dtest=AuctionServiceTest test",
    arrange: "Seed item/auction state ban đầu và request create/cancel phù hợp.",
    act: "Gọi createAuction, getAuctions/getAuction hoặc cancelAuction.",
    assert: "Response và status auction phải khớp với rule business trong service.",
    viva: "Nếu giảng viên hỏi CANCEL_AUCTION có side effect gì, nói test này rồi nối sang observer flow.",
  },
  {
    name: "BidServiceConcurrencyTest",
    target: "Chứng minh per-auction lock chống lost update khi nhiều bidder đặt giá cùng lúc.",
    command: ".\\mvnw.cmd -pl auction-server -Dtest=BidServiceConcurrencyTest test",
    arrange: "Tạo một auction RUNNING và nhiều thread hoặc bidder cùng nhắm vào auctionId đó.",
    act: "Gọi placeBid cạnh tranh trong cùng cửa sổ thời gian.",
    assert: "currentPrice/highestBidder vẫn hợp lệ, không có interleaving phá invariant.",
    viva: "Đây là bằng chứng mạnh nhất cho phần concurrency của repo; đừng chỉ kể ReentrantLock bằng miệng.",
  },
  {
    name: "AuctionSchedulerTest",
    target: "Chứng minh start/end scheduler và anti-sniping reschedule đổi status đúng thời điểm.",
    command: ".\\mvnw.cmd -pl auction-server -Dtest=AuctionSchedulerTest test",
    arrange: "Tạo auction với start/end time kiểm soát được và scheduler state sạch.",
    act: "Schedule start/end hoặc extend end rồi chờ task chạy.",
    assert: "AuctionStatus đổi đúng và event side effect được kích hoạt theo expectation.",
    viva: "Khi bị hỏi OPEN -> RUNNING -> FINISHED vận hành ra sao, dùng test này làm bằng chứng thay vì chỉ nói scheduler có tồn tại.",
  },
  {
    name: "AuctionE2ETest",
    target: "Kiểm chứng luồng integration qua nhiều lớp thay vì chỉ từng service đơn lẻ.",
    command: ".\\mvnw.cmd -pl auction-server -Dtest=AuctionE2ETest test",
    arrange: "Dựng data và request đủ để đi qua handler/service/repository trong một flow hoàn chỉnh.",
    act: "Chạy scenario end-to-end mà test bao phủ.",
    assert: "Kết quả cuối cùng của flow đúng ở cả response và state persistence.",
    viva: "Nếu muốn chứng minh toàn chuỗi request -> handler -> service -> repository khớp nhau, đây là test nên mở.",
  },
];

export { projectLabel };
